#!/usr/bin/env bash
set -euo pipefail

# ──────────────────────────────────────────────────────────────
# sync-bmad-knowledge.sh
# Import domain knowledge from BMAD-METHOD into woos skill structure
#
# Usage:
#   ./scripts/sync-bmad-knowledge.sh [--bmad-path /path/to/BMAD-METHOD]
#
# Prerequisites:
#   - BMAD-METHOD repo cloned locally
#   - yq installed (brew install yq)
#
# What it does:
#   1. Reads sync-bmad-knowledge.yaml mapping config
#   2. For each skill mapping, copies BMAD assets into references/bmad/
#   3. Generates a SOURCES.md with version info and file manifest
#   4. All imported files go under references/bmad/ (never mixed with our own files)
#
# Re-runnable: deletes old bmad/ dir and re-syncs fresh each time
# ──────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG="$SCRIPT_DIR/sync-bmad-knowledge.yaml"

# Default BMAD path (sibling directory)
BMAD_ROOT="${BMAD_ROOT:-$(cd "$REPO_ROOT/../BMAD-METHOD" 2>/dev/null && pwd || echo "")}"

# Parse args
while [[ $# -gt 0 ]]; do
  case $1 in
    --bmad-path) BMAD_ROOT="$2"; shift 2 ;;
    --help|-h) echo "Usage: $0 [--bmad-path /path/to/BMAD-METHOD]"; exit 0 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

# Validate
if [[ -z "$BMAD_ROOT" || ! -d "$BMAD_ROOT" ]]; then
  echo "ERROR: BMAD-METHOD not found. Set --bmad-path or clone to sibling dir."
  echo "  git clone https://github.com/bmad-code-org/BMAD-METHOD.git ../BMAD-METHOD"
  exit 1
fi

if ! command -v yq &>/dev/null; then
  echo "ERROR: yq not installed. Run: brew install yq"
  exit 1
fi

# Get BMAD version info
BMAD_VERSION=$(cd "$BMAD_ROOT" && git describe --tags --always 2>/dev/null || echo "unknown")
BMAD_COMMIT=$(cd "$BMAD_ROOT" && git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BMAD_DATE=$(cd "$BMAD_ROOT" && git log -1 --format=%ci 2>/dev/null || echo "unknown")
SYNC_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "═══════════════════════════════════════════════════════════"
echo " BMAD Knowledge Sync"
echo " Source: $BMAD_ROOT"
echo " Version: $BMAD_VERSION ($BMAD_COMMIT)"
echo " Target: $REPO_ROOT/skills/product-design/"
echo "═══════════════════════════════════════════════════════════"
echo ""

SKILLS_DIR="$REPO_ROOT/skills/product-design"
TOTAL_FILES=0
TOTAL_SKILLS=0

# Read number of top-level mappings
MAPPING_COUNT=$(yq '.mappings | keys | length' "$CONFIG")

for i in $(seq 0 $((MAPPING_COUNT - 1))); do
  MAPPING_KEY=$(yq ".mappings | keys | .[$i]" "$CONFIG")

  # Determine target skill directory
  TARGET_SKILL=$(yq ".mappings.$MAPPING_KEY.target_skill // \"$MAPPING_KEY\"" "$CONFIG" | tr -d '"')
  SUBFOLDER=$(yq ".mappings.$MAPPING_KEY.subfolder // \"\"" "$CONFIG" | tr -d '"')

  if [[ -n "$SUBFOLDER" ]]; then
    TARGET_DIR="$SKILLS_DIR/$TARGET_SKILL/references/bmad/$SUBFOLDER"
  else
    TARGET_DIR="$SKILLS_DIR/$TARGET_SKILL/references/bmad"
  fi

  # Check if target skill exists
  if [[ ! -d "$SKILLS_DIR/$TARGET_SKILL" ]]; then
    echo "⚠️  SKIP $MAPPING_KEY → skill dir '$TARGET_SKILL' not found"
    continue
  fi

  # Clean and recreate
  rm -rf "$TARGET_DIR"
  mkdir -p "$TARGET_DIR/personas" "$TARGET_DIR/frameworks" "$TARGET_DIR/templates" "$TARGET_DIR/rubrics" "$TARGET_DIR/examples"

  SKILL_FILES=0

  # Copy each category
  for CATEGORY in personas frameworks templates rubrics examples; do
    COUNT=$(yq ".mappings.$MAPPING_KEY.$CATEGORY | length // 0" "$CONFIG")
    if [[ "$COUNT" == "0" || "$COUNT" == "null" ]]; then
      continue
    fi

    for j in $(seq 0 $((COUNT - 1))); do
      REL_PATH=$(yq ".mappings.$MAPPING_KEY.$CATEGORY[$j]" "$CONFIG" | tr -d '"')
      SRC="$BMAD_ROOT/$REL_PATH"

      if [[ ! -f "$SRC" ]]; then
        echo "  ⚠️  NOT FOUND: $REL_PATH"
        continue
      fi

      # Flatten filename: replace / with -- for readability
      BASENAME=$(basename "$REL_PATH")
      # If there are name collisions, prefix with parent dir
      PARENT=$(basename "$(dirname "$REL_PATH")")
      DEST_NAME="${PARENT}--${BASENAME}"

      cp "$SRC" "$TARGET_DIR/$CATEGORY/$DEST_NAME"
      SKILL_FILES=$((SKILL_FILES + 1))
    done
  done

  # Remove empty category dirs
  find "$TARGET_DIR" -type d -empty -delete 2>/dev/null || true

  # Generate SOURCES.md
  cat > "$TARGET_DIR/SOURCES.md" << EOF
# BMAD Knowledge Import — $MAPPING_KEY

> Auto-generated by \`scripts/sync-bmad-knowledge.sh\`
> Do NOT edit manually — changes will be overwritten on next sync.

## Source

- **BMAD Version:** $BMAD_VERSION
- **Commit:** $BMAD_COMMIT
- **Date:** $BMAD_DATE
- **Synced:** $SYNC_DATE

## Files Imported

EOF

  # List all imported files
  find "$TARGET_DIR" -type f -name "*.md" -o -name "*.toml" -o -name "*.csv" | sort | while read -r f; do
    REL=$(echo "$f" | sed "s|$TARGET_DIR/||")
    echo "- \`$REL\`" >> "$TARGET_DIR/SOURCES.md"
  done

  echo "✅ $MAPPING_KEY → $TARGET_SKILL ($SKILL_FILES files)"
  TOTAL_FILES=$((TOTAL_FILES + SKILL_FILES))
  TOTAL_SKILLS=$((TOTAL_SKILLS + 1))
done

echo ""
echo "═══════════════════════════════════════════════════════════"
echo " Done! $TOTAL_FILES files imported across $TOTAL_SKILLS skill mappings"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Next steps:"
echo "  1. Review imported files: git diff --stat"
echo "  2. Commit: git add -A && git commit -m 'chore: sync BMAD knowledge ($BMAD_VERSION)'"
